subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 2
      leftSlaveOne: 1
      leftSlaveTwo: 3
      rightMain: 7
      rightSlaveOne: 5
      rightSlaveTwo: 6
  climber:
    implemented: false
    talons:
      one: 8
  cargoshooter:
    implemented: false
    talons:
      arm: 4
      intake: 8
  constants:
    kP: 0.116
    kI: 0
    kD: 1.16
    kF: 0.128
    maxPos: 1475
    minPos: 915
