subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 14
      leftSlaveOne: 13
      leftSlaveTwo: 15
      rightMain: 1
      rightSlaveOne: 0
      rightSlaveTwo: 2
  climber:
    implemented: false
    talons:
      one: 8
