subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 14
      leftSlaveOne: 13
      rightMain: 1
      rightSlaveOne: 2
    victors:
      rightSlaveTwo: 0
      leftSlaveTwo: 15
  climber:
    implemented: false
    talons:
      one: 8
