subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 14
      leftSlaveOne: 13
      rightMain: 1
      rightSlaveOne: 2
    victors:
      rightSlaveTwo: 0
      leftSlaveTwo: 15
  climber:
    implemented: false
    talons:
      climbMaster: 3
      climbSlave: 12
    doubleSolenoids:
      habPiston:
        forward: 4
        reverse: 5
  cargocollector:
    implemented: false
    talons:
      intake: 11
    solenoids:
      arm: 2
  birdbeak:
    implemented: false
    talons:
      hatchIntake: 4
    solenoids:
      beak: 0
      puncher: 2
      arm: 3
  cargoshooter:
    implemented: false
    talons:
      arm: 5
      intake: 10
    constants:
      kP: 5.0
      kI: 0
      kD: 1.0
      kF: 0
      maxPos: 1475
      minPos: 915
pcm: 17
constants:
  wheelbase: 25
  ticksPerRev: 1025
  ticksPerIn: 50
  maxVel: 800
