subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 14
      leftSlaveOne: 13
      rightMain: 1
      rightSlaveOne: 2
    victors:
      rightSlaveTwo: 0
      leftSlaveTwo: 15
  climber:
    implemented: false
    talons:
      climbMaster: -1
      climbSlave: -1
  cargocollector:
    implemented: false
    talons:
      intake: -1
  birdbeak:
    implemented: false
    talons:
      hatchIntake: -1


